[project]
name = "math-6388"
version = "0.1.0"
description = "For all work related to math 6388 - statistical and machine learning"
authors = [
    {name = "Brady Lamson",email = "lamsonbrady@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
